server:
  port: 8081

# database 연동 설정 
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/testdb
    username: root
    password: 1234
  thymeleaf:
    cache: false
    
# spring data jpa 설정        
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create